name: rpg_app
description: "An interactive RPG application built with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adapt based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  # UI Packages
  cupertino_icons: ^1.0.6 # Standard iOS icons

  # Networking
  http: ^1.2.1 # For making HTTP requests (e.g., to AI API)

  # State Management (Example: Provider)
  provider: ^6.1.2 # A popular choice for state management

  # JSON Handling (Built-in with dart:convert, but good practice)
  # No extra package needed initially, dart:convert is sufficient

  # For reading local files (Backend Simulation)
  path_provider: ^2.1.3 # To get directory paths

  # For simple key-value storage (used for first launch flag)
  shared_preferences: ^2.2.3 # Check pub.dev for latest version

  # For Play Store Integration (Placeholder - requires setup)
  # in_app_purchase: ^3.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.0 # Replacing mockito with mocktail
  test: ^1.24.0 # Ensure test package is available

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages